### ISSUE TITLE
[BUG] 点击图片大图之后有概率会导致界面无响应

### ISSUE THREAD

**Issue by Revincx** [czy0729/Bangumi#100]
在详情页面点开条目的封面或者截图的大图预览之后，有一定概率过一段事件后界面无响应。

录屏：

https://user-images.githubusercontent.com/25524750/235704158-001ab623-a0d0-47b9-add6-7f67b38fd978.mp4

使用 ADB Logcat 获取了一段日志，不知道有没有用：
```
--------- beginning of main
05-02 22:42:48.916 19980 19980 E unknown:NativeViewHierarchyManager: Unable to update properties for view tag 5673
05-02 22:42:48.916 19980 19980 E unknown:NativeViewHierarchyManager: com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 5673 could not be found.
05-02 22:42:48.916 19980 19980 E unknown:NativeViewHierarchyManager: 
05-02 22:42:48.916 19980 19980 E unknown:NativeViewHierarchyManager:    at com.facebook.react.uimanager.NativeViewHierarchyManager.resolveViewManager(NativeViewHierarchyManager.java:3)
05-02 22:42:48.916 19980 19980 E unknown:NativeViewHierarchyManager:    at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:2)
05-02 22:42:48.916 19980 19980 E unknown:NativeViewHierarchyManager:    at com.facebook.react.uimanager.UIImplementation.synchronouslyUpdateViewOnUIThread(UIImplementation.java:2)
05-02 22:42:48.916 19980 19980 E unknown:NativeViewHierarchyManager:    at com.swmansion.reanimated.c.M(NodesManager.java:12)
05-02 22:42:48.916 19980 19980 E unknown:NativeViewHierarchyManager:    at com.swmansion.reanimated.NativeProxy.updateProps(NativeProxy.java:1)
05-02 22:42:48.916 19980 19980 E unknown:NativeViewHierarchyManager:    at com.swmansion.reanimated.NativeProxy$AnimationFrameCallback.onAnimationFrame(Native Method)
05-02 22:42:48.916 19980 19980 E unknown:NativeViewHierarchyManager:    at com.swmansion.reanimated.c.z(NodesManager.java:9)
05-02 22:42:48.916 19980 19980 E unknown:NativeViewHierarchyManager:    at com.swmansion.reanimated.c.a(NodesManager.java:1)
05-02 22:42:48.916 19980 19980 E unknown:NativeViewHierarchyManager:    at com.swmansion.reanimated.c$a.doFrameGuarded(NodesManager.java:1)
05-02 22:42:48.916 19980 19980 E unknown:NativeViewHierarchyManager:    at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:1)
05-02 22:42:48.916 19980 19980 E unknown:NativeViewHierarchyManager:    at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:7)
05-02 22:42:48.916 19980 19980 E unknown:NativeViewHierarchyManager:    at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:1)
05-02 22:42:48.916 19980 19980 E unknown:NativeViewHierarchyManager:    at android.view.Choreographer$CallbackRecord.run(Unknown Source:12)
05-02 22:42:48.916 19980 19980 E unknown:NativeViewHierarchyManager:    at android.view.Choreographer.doCallbacks(Unknown Source:84)
05-02 22:42:48.916 19980 19980 E unknown:NativeViewHierarchyManager:    at android.view.Choreographer.doFrame(Unknown Source:307)
05-02 22:42:48.916 19980 19980 E unknown:NativeViewHierarchyManager:    at android.view.Choreographer$FrameDisplayEventReceiver.run(Unknown Source:11)
05-02 22:42:48.916 19980 19980 E unknown:NativeViewHierarchyManager:    at android.os.Handler.handleCallback(Unknown Source:2)
05-02 22:42:48.916 19980 19980 E unknown:NativeViewHierarchyManager:    at android.os.Handler.dispatchMessage(Unknown Source:4)
05-02 22:42:48.916 19980 19980 E unknown:NativeViewHierarchyManager:    at android.os.Looper.loopOnce(Unknown Source:176)
05-02 22:42:48.916 19980 19980 E unknown:NativeViewHierarchyManager:    at android.os.Looper.loop(Unknown Source:76)
05-02 22:42:48.916 19980 19980 E unknown:NativeViewHierarchyManager:    at android.app.ActivityThread.main(Unknown Source:138)
05-02 22:42:48.916 19980 19980 E unknown:NativeViewHierarchyManager:    at java.lang.reflect.Method.invoke(Native Method)
05-02 22:42:48.916 19980 19980 E unknown:NativeViewHierarchyManager:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
05-02 22:42:48.916 19980 19980 E unknown:NativeViewHierarchyManager:    at com.android.internal.os.ZygoteInit.main(Unknown Source:309)
05-02 22:42:49.018 19980 19980 W unknown:WrappingUtils: Don't know how to round that drawable: com.facebook.react.views.image.ReactImageDownloadListener$EmptyDrawable@1716c74
05-02 22:42:49.038 19980 20173 D SoLoader: About to load: libnative-imagetranscoder.so
05-02 22:42:49.038 19980 20173 D SoLoader: libnative-imagetranscoder.so not found on /data/data/com.czy0729.bangumi/lib-main
05-02 22:42:49.038 19980 20173 D SoLoader: libnative-imagetranscoder.so found on /data/app/~~6a2duCLrF1ywSVzf83QCsQ==/com.czy0729.bangumi-O50G4pBAUVyg6GZ_2s4Xtg==/lib/arm64
05-02 22:42:49.038 19980 20173 D SoLoader: Not resolving dependencies for libnative-imagetranscoder.so
05-02 22:42:49.041 19980 20173 D SoLoader: Loaded: libnative-imagetranscoder.so
05-02 22:42:49.058 19980 20175 D SoLoader: About to load: libnative-filters.so
05-02 22:42:49.058 19980 20175 D SoLoader: libnative-filters.so not found on /data/data/com.czy0729.bangumi/lib-main
05-02 22:42:49.059 19980 20175 D SoLoader: libnative-filters.so found on /data/app/~~6a2duCLrF1ywSVzf83QCsQ==/com.czy0729.bangumi-O50G4pBAUVyg6GZ_2s4Xtg==/lib/arm64
05-02 22:42:49.059 19980 20175 D SoLoader: Not resolving dependencies for libnative-filters.so
05-02 22:42:49.060 19980 20175 D SoLoader: Loaded: libnative-filters.so
05-02 22:42:49.874 19980 19980 E unknown:FabricViewStateManager: setState called without a StateWrapper
05-02 22:43:10.669 19980 19980 I libc    : Requested dump for tid 19980 (czy0729.bangumi)
05-02 22:43:12.622 19980 19980 I libc    : Requested dump for tid 19980 (czy0729.bangumi)
05-02 22:43:17.780 19980 19980 E unknown:ReactModalHost: Creating new dialog from context: com.czy0729.bangumi.MainActivity@58c83@363651
05-02 22:43:17.781 19980 19980 D IS_CTS_MODE: false
05-02 22:43:17.781 19980 19980 D MULTI_WINDOW_SWITCH_ENABLED: false
05-02 22:43:17.788 19980 19980 D DecorView[]: updateDecorCaptionStatus displayWindowDecor is false
05-02 22:43:17.894 19980 20113 E BLASTBufferQueue: [ViewRootImpl[MainActivity]#0](f:0,a:3) transactionCallback received for a newer framenumber=231 than expected=230
05-02 22:43:17.904 19980 19980 E unknown:ReactModalHost: Updating existing dialog with context: com.czy0729.bangumi.MainActivity@58c83@363651
05-02 22:43:17.941 19980 19980 D DecorView[]: onWindowFocusChanged hasWindowFocus false
05-02 22:43:17.997 19980 19980 D DecorView[]: onWindowFocusChanged hasWindowFocus true
05-02 22:43:20.393 19980 19980 D MIUIInput: [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x8, repeatCount=0, eventTime=152737213, downTime=152737213, deviceId=-1, source=0x101, displayId=0 }
05-02 22:43:20.400 19980 19980 D MIUIInput: [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x8, repeatCount=0, eventTime=152737213, downTime=152737213, deviceId=-1, source=0x101, displayId=0 }
--------- beginning of system
05-02 22:43:24.507 19980 19999 W MIUIScout App: Enter APP_SCOUT_WARNING State
05-02 22:43:24.509 19980 20244 W MIUIScout App: Event:APP_SCOUT_WARNING Thread:main backtrace:
05-02 22:43:24.509 19980 20244 W MIUIScout App:     at android.graphics.HardwareRenderer.nSetStopped(Native Method)
05-02 22:43:24.509 19980 20244 W MIUIScout App:     at android.graphics.HardwareRenderer.setStopped(Unknown Source:2)
05-02 22:43:24.509 19980 20244 W MIUIScout App:     at android.view.ViewRootImpl.performDraw(Unknown Source:173)
05-02 22:43:24.509 19980 20244 W MIUIScout App:     at android.view.ViewRootImpl.performTraversals(Unknown Source:2719)
05-02 22:43:24.509 19980 20244 W MIUIScout App:     at android.view.ViewRootImpl.doTraversal(Unknown Source:36)
05-02 22:43:24.509 19980 20244 W MIUIScout App:     at android.view.ViewRootImpl$TraversalRunnable.run(Unknown Source:2)
05-02 22:43:24.509 19980 20244 W MIUIScout App:     at android.view.Choreographer$CallbackRecord.run(Unknown Source:20)
05-02 22:43:24.509 19980 20244 W MIUIScout App:     at android.view.Choreographer.doCallbacks(Unknown Source:84)
05-02 22:43:24.509 19980 20244 W MIUIScout App:     at android.view.Choreographer.doFrame(Unknown Source:328)
05-02 22:43:24.509 19980 20244 W MIUIScout App:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Unknown Source:11)
05-02 22:43:24.509 19980 20244 W MIUIScout App:     at android.os.Handler.handleCallback(Unknown Source:2)
05-02 22:43:24.509 19980 20244 W MIUIScout App:     at android.os.Handler.dispatchMessage(Unknown Source:4)
05-02 22:43:24.509 19980 20244 W MIUIScout App:     at android.os.Looper.loopOnce(Unknown Source:176)
05-02 22:43:24.509 19980 20244 W MIUIScout App:     at android.os.Looper.loop(Unknown Source:76)
05-02 22:43:24.509 19980 20244 W MIUIScout App:     at android.app.ActivityThread.main(Unknown Source:138)
05-02 22:43:24.509 19980 20244 W MIUIScout App:     at java.lang.reflect.Method.invoke(Native Method)
05-02 22:43:24.509 19980 20244 W MIUIScout App:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
05-02 22:43:24.509 19980 20244 W MIUIScout App:     at com.android.internal.os.ZygoteInit.main(Unknown Source:309)
05-02 22:43:24.526 19980 19987 I czy0729.bangum: Thread[5,tid=19987,WaitingInMainSignalCatcherLoop,Thread*=0xb40000782f619c00,peer=0x141c0000,"Signal Catcher"]: reacting to signal 3
05-02 22:43:24.526 19980 19987 I czy0729.bangum: 
05-02 22:43:24.754 19980 19987 I czy0729.bangum: Wrote stack traces to tombstoned
05-02 22:43:25.718 19980 20216 D MIUIScout ANR: get period history msg: (Current message: duration=5269ms seq=5719 late=2ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
05-02 22:43:25.718 19980 20216 D MIUIScout ANR: get period history msg:messages for the same target android.view.Choreographer$FrameHandler execute time>50ms (count=442 totalwalltime=673ms h=android.view.Choreographer$FrameHandler whatORcallback=android.view.Choreographer$FrameDisplayEventReceiver)
05-02 22:43:25.718 19980 20216 D MIUIScout ANR: get period history msg:execute time>50ms (msgIndex=332seq=5538 plan=22:43:17.935 late=9ms wall=53ms running=0ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
05-02 22:43:25.718 19980 20216 D MIUIScout ANR: get period history msg:execute time>50ms (msgIndex=296seq=5502 plan=22:43:17.768 late=1ms wall=134ms running=0ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
05-02 22:43:25.718 19980 20216 D MIUIScout ANR: get period history msg:In recent 20s, total historyMsgCount=512
05-02 22:43:25.719 19980 20216 W MIUIScout ANR: Print Message Id: 0 MessageInfo: { when=-5s269ms callback=com.facebook.drawee.components.DeferredReleaserConcurrentImpl$1 target=android.os.Handler }
05-02 22:43:25.719 19980 20216 W MIUIScout ANR: Print Message Id: 1 MessageInfo: { when=-5s264ms callback=android.graphics.drawable.AnimatedVectorDrawable$VectorDrawableAnimatorRT$$ExternalSyntheticLambda0 target=android.os.Handler }
05-02 22:43:25.719 19980 20216 W MIUIScout ANR: Print Message Id: 2 MessageInfo: { when=-5s246ms what=31 obj=com.android.internal.os.SomeArgs@7e3a7c8 target=android.view.ViewRootImpl$ViewRootHandler }
05-02 22:43:25.719 19980 20216 W MIUIScout ANR: Print Message Id: 3 MessageInfo: { when=-5s246ms what=31 obj=com.android.internal.os.SomeArgs@5bd9061 target=android.view.ViewRootImpl$ViewRootHandler }
05-02 22:43:25.719 19980 20216 W MIUIScout ANR: Print Message Id: 4 MessageInfo: { when=-5s244ms what=30 obj=com.android.internal.os.SomeArgs@fba3786 target=android.view.ViewRootImpl$ViewRootHandler }
05-02 22:43:25.719 19980 20216 W MIUIScout ANR: (Print messages: 5, polling=false, quitting=false)
05-02 22:43:26.368 19980 19987 I czy0729.bangum: Thread[5,tid=19987,WaitingInMainSignalCatcherLoop,Thread*=0xb40000782f619c00,peer=0x141c0000,"Signal Catcher"]: reacting to signal 3
05-02 22:43:26.369 19980 19987 I czy0729.bangum: 
05-02 22:43:26.572 19980 19987 I czy0729.bangum: Wrote stack traces to tombstoned
05-02 22:43:27.008 19980 19999 W MIUIScout App: Enter APP_SCOUT_HANG state
05-02 22:43:27.010 19980 20250 W MIUIScout App: Event:APP_SCOUT_HANG Thread:main backtrace:
05-02 22:43:27.010 19980 20250 W MIUIScout App:     at android.graphics.HardwareRenderer.nSetStopped(Native Method)
05-02 22:43:27.010 19980 20250 W MIUIScout App:     at android.graphics.HardwareRenderer.setStopped(Unknown Source:2)
05-02 22:43:27.010 19980 20250 W MIUIScout App:     at android.view.ViewRootImpl.performDraw(Unknown Source:173)
05-02 22:43:27.010 19980 20250 W MIUIScout App:     at android.view.ViewRootImpl.performTraversals(Unknown Source:2719)
05-02 22:43:27.010 19980 20250 W MIUIScout App:     at android.view.ViewRootImpl.doTraversal(Unknown Source:36)
05-02 22:43:27.010 19980 20250 W MIUIScout App:     at android.view.ViewRootImpl$TraversalRunnable.run(Unknown Source:2)
05-02 22:43:27.010 19980 20250 W MIUIScout App:     at android.view.Choreographer$CallbackRecord.run(Unknown Source:20)
05-02 22:43:27.010 19980 20250 W MIUIScout App:     at android.view.Choreographer.doCallbacks(Unknown Source:84)
05-02 22:43:27.010 19980 20250 W MIUIScout App:     at android.view.Choreographer.doFrame(Unknown Source:328)
05-02 22:43:27.010 19980 20250 W MIUIScout App:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Unknown Source:11)
05-02 22:43:27.010 19980 20250 W MIUIScout App:     at android.os.Handler.handleCallback(Unknown Source:2)
05-02 22:43:27.010 19980 20250 W MIUIScout App:     at android.os.Handler.dispatchMessage(Unknown Source:4)
05-02 22:43:27.010 19980 20250 W MIUIScout App:     at android.os.Looper.loopOnce(Unknown Source:176)
05-02 22:43:27.010 19980 20250 W MIUIScout App:     at android.os.Looper.loop(Unknown Source:76)
05-02 22:43:27.010 19980 20250 W MIUIScout App:     at android.app.ActivityThread.main(Unknown Source:138)
05-02 22:43:27.010 19980 20250 W MIUIScout App:     at java.lang.reflect.Method.invoke(Native Method)
05-02 22:43:27.010 19980 20250 W MIUIScout App:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
05-02 22:43:27.010 19980 20250 W MIUIScout App:     at com.android.internal.os.ZygoteInit.main(Unknown Source:309)
05-02 22:43:27.030 19980 19987 I czy0729.bangum: Thread[5,tid=19987,WaitingInMainSignalCatcherLoop,Thread*=0xb40000782f619c00,peer=0x141c0000,"Signal Catcher"]: reacting to signal 3
05-02 22:43:27.030 19980 19987 I czy0729.bangum: 
05-02 22:43:27.225 19980 19987 I czy0729.bangum: Wrote stack traces to tombstoned
05-02 22:43:29.822 19980 19980 I libc    : Requested dump for tid 19980 (czy0729.bangumi)
```

因为没法稳定复现，上面日志所对应的操作不是视频中的，而是另一次复现时的日志。对应操作应该是：从主页点进条目详情页面 -> 点开封面大图 -> 等待数秒。

因为配环境太麻烦没有尝试本地调试环境下复现并抓取日志，如果有需要的话我可以试试把代码拉下来跑一下试试。

**Comment by czy0729** [comment]
OK 我看看
