### ISSUE TITLE
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

### ISSUE THREAD

**Issue by leekay0032** [czy0729/Bangumi#129]
> Task :app:createBundleReleaseJsAndAssets
Error: Unable to resolve module react-native-svg from D:\rn-project\Bangumi\src\components\squircle\index.tsx: react-native-svg could not be found within the project or in these directories:
  node_modules
   6 |  */
   7 | import React from 'react'
>  8 | import Svg, { Defs, ClipPath, Path } from 'react-native-svg'
     |                                            ^
   9 | import MaskedView from '@react-native-masked-view/masked-view'
  10 | import { _ } from '@stores'
  11 | import { IOS } from '@constants'
Error: Unable to resolve module react-native-svg from D:\rn-project\Bangumi\src\components\squircle\index.tsx: react-native-svg could not be found within the project or in these directories:
  node_modules
   6 |  */
   7 | import React from 'react'
>  8 | import Svg, { Defs, ClipPath, Path } from 'react-native-svg'
     |                                            ^
   9 | import MaskedView from '@react-native-masked-view/masked-view'
  10 | import { _ } from '@stores'
  11 | import { IOS } from '@constants'
    at ModuleResolver.resolveDependency (D:\rn-project\Bangumi\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:139:15)
    at DependencyGraph.resolveDependency (D:\rn-project\Bangumi\node_modules\metro\src\node-haste\DependencyGraph.js:277:43)
    at Object.resolve (D:\rn-project\Bangumi\node_modules\metro\src\lib\transformHelpers.js:169:21)
    at Graph._resolveDependencies (D:\rn-project\Bangumi\node_modules\metro\src\DeltaBundler\Graph.js:473:35)
    at Graph._processModule (D:\rn-project\Bangumi\node_modules\metro\src\DeltaBundler\Graph.js:261:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Graph._addDependency (D:\rn-project\Bangumi\node_modules\metro\src\DeltaBundler\Graph.js:372:20)
    at async Promise.all (index 57)
    at async Graph._processModule (D:\rn-project\Bangumi\node_modules\metro\src\DeltaBundler\Graph.js:322:5)
    at async Graph._addDependency (D:\rn-project\Bangumi\node_modules\metro\src\DeltaBundler\Graph.js:372:20)

> Task :app:createBundleReleaseJsAndAssets FAILED
w: Detected multiple Kotlin daemon sessions at build\kotlin\sessions

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:createBundleReleaseJsAndAssets'.
> Process 'command 'cmd'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.0.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4m 32s
1243 actionable tasks: 1070 executed, 173 up-to-date
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Windows 11 
JDK 11
NODE 18.11.0

在打包android包时出现这个错误，你们有遇到的吗？

**Comment by czy0729** [comment]
你可以把 tag 转到 8.3.1 的时候再试试打包，https://github.com/czy0729/Bangumi/tree/8.3.1

**Comment by leekay0032** [comment]
可以，解决了
